### ISSUE TITLE
Only renders 10 colums

### ISSUE THREAD

**Issue by jiggycreationz** [chuckhendo/chrome-bootstrap#3]
Hi
for some reason it's rendering only 10 columns with massive gaps (unlike the google chrome preview)

 ![bs3-overlay-issue](https://cloud.githubusercontent.com/assets/4390630/5505218/7edc336e-8786-11e4-8aeb-2ab454b9086b.jpg)

**Comment by chuckhendo** [comment]
@jiggycreationz Does it only appear to be happening on this site? 

What seems to be happening is that the overlay applies divs with classes that work on Bootstrap 2 and Bootstrap 3. For some reason, this site has stylesheets being called for Bootstrap 2 AND Bootstrap 3, which is causing both set of styles to be applied

**Comment by jiggycreationz** [comment]
Ok. Thanks i'll look into it :+1: :)

**Comment by chuckhendo** [comment]
I'm going to close this issue. If you feel this is still an issue, please reopen the issu.
